
CONFIG_VFD_SUPPORT=m
CONFIG_VFD_NO_KEY_INPUT=m
# CONFIG_VFD_NO_DELAYS is not set
CONFIG_VFD_PT6964=m
# CONFIG_VFD_PT6964_X92 is not set
CONFIG_VFD_PT6964_T95U=m

EXTRA_CFLAGS  := -g -Wall -DCONFIG_VFD_PT6964_T95U -DCONFIG_VFD_SUPPORT_MODULE
EXTRA_CFLAGS  += -DDEBUG


obj-$(CONFIG_VFD_PT6964)                += pt6964.o
obj-$(CONFIG_VFD_PT6964_X92)            += vfd-ca.o
obj-$(CONFIG_VFD_PT6964_T95U)           += vfd-cc.o

obj-$(CONFIG_VFD_SUPPORT)      := vfdmod.o
vfdmod-$(CONFIG_VFD_SUPPORT)   := vfd.o vfd-glyphs.o pt6964.o vfd-cc.o

