#
# Makefile for the VFD drivers.
#

obj-$(CONFIG_VFD_SUPPORT)		+= vfd.o vfd-glyphs.o

obj-$(CONFIG_VFD_PT6964)		+= pt6964.o
obj-$(CONFIG_VFD_PT6964_X92)		+= vfd-ca.o
obj-$(CONFIG_VFD_PT6964_T95U)		+= vfd-cc.o
